name: Build and push Docker image

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./build/Dockerfile
          tags: ghcr.io/ilcm96/docker-blue-green-deployment:latest
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: ilcm96/github-action-ssh@main
        with:
          command: bash /home/ubuntu/blue-green.sh
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
